### ISSUE TITLE
Traffic not always visible in ForeFlight

### ISSUE THREAD

**Issue by wiseman** [astenlund/fs2ff#1]
First, thank you!  This is great, and thank you for doing it.

I'm using FS2020 and ForeFlight. Currently I'm seeing "live" (ADS-B) traffic that FS2020 imports from Flightaware or whatever on ForeFlight, but I don't think I'm seeing any other player traffic.  Here's an example of traffic that doesn't show up in ForeFlight:

```
0 XTRAFFICMSFS,1,34.04482,-118.25918,1359.8,-2099.9,1,80.528,120.4,AS-XGSK
```

And here's traffic that does:
```
12.2 XTRAFFICMSFS,17171,33.94483,-118.43457,126.3,0,0,259.889,0,Southwest 1324
```

(The `0` and `12.2` are the distances in miles from me to the traffic; I print it just for debugging purposes and don't send it to ForeFlight.)

The only thing that sticks out is the ID, 1, of AS-XGSK. I mean, 17171 isn't a valid ICAO either as far as I know; It's not possible that ForeFlight cares about the ICAO, is it?

**Comment by wiseman** [comment]
Also, since I see that traffic support is new, I'll mention another weird thing I see: A bunch of player aircraft seem to be coming in with latitude 0, longitude 0.

**Comment by astenlund** [comment]
John,

Thank you for this information, I will check it out as time permits!

Sincerely,
Andreas Stenlund

**Comment by wiseman** [comment]
Digging into this some more, I realized that AS-XGSK was my aircraft, so I guess that's why I'm not seeing it. I think there are still players flying in the sim that I don't see in ForeFlight, but I'll have to do more testing to confirm that. There are definitely still aircraft with coordinates (0, 0).

**Comment by astenlund** [comment]
Just going to the main menu and connecting the fs2ff app indeed gives me two objects (id 0 and 1) with Lat/Lon of 0 degrees. I have no idea what those objects are, but I guess at least one of them is my own aircraft. In that case, those coordinates should no longer show up once the player has spawned at an airport. Will have to test that later.

**Comment by astenlund** [comment]
The missing traffic is apparently a bug (or missing feature) in the SimConnect SDK, so nothing that I can do anything about. XMapsy has the same issue. Re-open if this is still not working after a fix has been announced by Asobo/Microsoft.

**Comment by wiseman** [comment]
Thanks for the info. I'll keep an eye out for changes.
