### ISSUE TITLE
Not showing app window

### ISSUE THREAD

**Issue by djmediko** [astenlund/fs2ff#20]
I downloaded the exe file and am using Windows 10.  I followed instructions to allow run and disabled the private network firewall.  I double click on file but nothing opens up.  Am I missing something?

**Comment by astenlund** [comment]
I'm not sure why this happened, but another user had the same problem. He/she solved it by installing Microsoft Visual C++ 2015 redistributable. It shouldn't be needed, but there might be a bug in .NET Core, or your system files might be corrupt.

To check your system files, open a command prompt as Admin and run the following command: `sfc /scannow`

The C++ resdist can be downloaded from Microsoft's [Download Center](https://www.microsoft.com/en-us/download/details.aspx?id=52685)

Hope this helps!

**Comment by djmediko** [comment]
That worked after I read his post. Working great now. Thank you for such a great piece of software. 

Richard Aballay

**Comment by astenlund** [comment]
v0.1.11 now has the required files bundled, so there is no longer any need to install the redist from Microsoft. It turns out that the Flight Simulator SDK had this dependency.
