### ISSUE TITLE
Flight log shows 0/0 end point for flight

### ISSUE THREAD

**Issue by mkeefe** [astenlund/fs2ff#23]
First off, I love the software, it makes sim flying so much more fun and practical. I noticed ForeFlight has an option to track a flight, and it shows my departing airport, the path I took (pattern work) and right after the landing point the track line shoots from Boston to left of Africa.

I wouldn't consider this a make/break bug, just wanted to notate it in case someone else stumbles on it.

**Comment by astenlund** [comment]
Thanks for the feedback!

The game seems to be sending the coordinates 00N000W when in the top level menu. I guess I should filter these packets out, as they are of no value.

**Comment by mkeefe** [comment]
Oh, interesting so the 0/0 would actually be the beginning of my journey, then it located my actual position on the airport but drew a course. Wonder why they (FS 2020) would output that on the main menu?

**Comment by astenlund** [comment]
Fixed in v0.1.12.
