### ISSUE TITLE
Exe sometimes crashes when closing FS 2020

### ISSUE THREAD

**Issue by mkeefe** [astenlund/fs2ff#24]
After leaving a session and closing FS 2020 the fs2ff exe crashes. I am not sure how verbose the crash log is, but i'm happy to share if it left something on my machine which I can upload.

This of course doesn't affect playability, really just a minor issue but wanted to mention it.

Steps to reproduce:
1. Open FS 2020
2. Once on the main screen, open fs2ff exe
3. Go into a flight, fly around
4. Hit ESC, leave session.
5. On main screen exit out of FS 2020
6. App will *sometimes* crash

**Comment by astenlund** [comment]
Thanks for sharing your feedback.

By crash, do you mean a total crash where the window closes and the exe is terminated? If you know when this happened, you should be able to find the crash log in Event Viewer. Click Windows Logs -> Application. You might have to scroll a bit.

**Comment by mkeefe** [comment]
Hi, yes. Total crash. When i'm back home i'll grab that crash log for you.

**Comment by mkeefe** [comment]
Has not happened since. Going to close and will update if it crops up again.
