### ISSUE TITLE
working with P3D v5

### ISSUE THREAD

**Issue by henrylzy** [astenlund/fs2ff#35]
First of all, this is not a bug report.

The program itself won't work with P3D so I used P3D's LockheedMartin.Prepar3D.SimConnect.dll instead. Since P3D doesn't have a simconnect.dll(not in the SDK either), I just changed the name of P3D's dll to simconnect.dll, didn't change a single line of the codes, and it works, until it doesn't.

Everything looks normal, sometimes the traffic will have a 999+ altitude difference with the user aircraft, or sometimes ground aircraft will show up as airborne aircraft, I assume it was caused by the differences of simconnect.dll's version, or the absence or the real simconnect.dll. However it was solved by simply restarting the program.

The real problem that I have is the program will disconnect with P3D again and again, even though P3D is still running. At this point I have no idea what went wrong since I only know a little about coding and c#. All I was trying to achieve is to get this working with P3D, since I rarely fly with MSFS.

I really appreciate if you could take a look at this.

**Comment by astenlund** [comment]
Thank you for your interest.

P3D already has built-in support for GPS data broadcast, and should work out-of-the box. See the [ForeFlight Support Page](https://support.foreflight.com/hc/en-us/articles/204115345-How-do-I-connect-to-Prepar3D-Flight-Simulator-) for more information. If that doesn't work for you, I recommend looking for other software that has been built specifically for P3D.

Good luck!
