### ISSUE TITLE
0.1.14 keeps crashing on me?

### ISSUE THREAD

**Issue by jeffdamp-wave** [astenlund/fs2ff#61]
Sim: FS2020
PC: AMD 5900X
GPU: 3090
VR: Reverb G2

The previous build was pretty solid for me this one seems to crash frequently (disappears).  I think it happens on landing, I assume this isn't by design?
1. Play sim
2. Land plane
3. Look for fs2ff running
Result:
the fs2ff process is gone.
Expected:
fs2ff should keep running after landing.

**Comment by astenlund** [comment]
I'm unable to reproduce the error, unfortunately. Will try some more during the weekend.

**Comment by jeffdamp-wave** [comment]
Interestingly enough I couldn't repro tonight either.  I'll keep an eye out for it. but will close this out.
