### ISSUE TITLE
Crashing WiFi

### ISSUE THREAD

**Issue by nrankin18** [astenlund/fs2ff#74]
A bit of a weird one here...
After running FS2FF for a while my entire router (MG7540) will stop working and need to be restarted. This causes everyone connected to lose internet until the router is reset.

**Comment by jeffdamp-wave** [comment]
That is odd the app is sending UDP traffic over port 49002.  Did you try setting the ip address of your EFB So it doesn't broadcast?

**Comment by jeffdamp-wave** [comment]
P.s. if that doesn't help you can try this fork of fs2ff that uses gdl90 protocol I stead of the text flight Sim protocol https://github.com/jeffdamp-wave/fs2ff/releases/tag/v1.1.16

**Comment by nrankin18** [comment]
I'll give that a shot, though it'll be a few days before I can try again. The issue is very intermittent.
