### ISSUE TITLE
Aircraft lagging 10 -20 seconds behind in SkyDemon

### ISSUE THREAD

**Issue by wadoadi** [astenlund/fs2ff#88]
not sure what has changed, PC has done many updates as has MSFS2020... but there is now around a 20sec lag between the sim aircraft and the displayed position in SkyDemon on my PC.

Could there be a message rate displayed for both the sim messages and the outbound broadcast?

any ideas?

Windows 11 
Ethernet connection to the router

Skydemon running on an Iphone 14 Pro

**Comment by jeffdamp-wave** [comment]
I don't think astenlund actively works on this project anymore. A while ago I made a fork and implemented GDL90 for both Stratux and Stratus emulation.  I just tested using my version with skydemon and it worked perfect (Ipad Mini).  You can build from here: https://github.com/jeffdamp-wave/fs2ff or use the release I built (built from my own computer so it won't be signed) https://github.com/jeffdamp-wave/fs2ff/releases/tag/v1.1.16

**Comment by wadoadi** [comment]
ah ok thanks, I will give your build ago...

**Comment by wadoadi** [comment]
the problem was fixed by uninstalling MSFS and reinstalling it! thinking back it occurred when I ended my game pass and upgraded MSFS to Delux by license key.

I'm successfully using @jeffdamp-wave Build and GDL90, thank you.
