### ISSUE TITLE
Is there an Xbox support?

### ISSUE THREAD

**Issue by spaily** [astenlund/fs2ff#93]
Can this fs2ff be installed in Xbox? Is there any other option that I can use to have same capabilities as fs2ff?

**Comment by jeffdamp-wave** [comment]
Short answer NO. Fs2ff uses the simconnect library to interface with msfs. Unfortunately this has to be done on the box running msfs. Xbox does not allow for running any processes on box to interface with msfs. Asobo would need to implement functionality to allow remote collection of data via a protocol.
